name: CI Pipeline - DevOps WebApp

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Basic HTML Check
        run: |
          echo "CI Started"
          if [ -f index.html ]; then
            echo "index.html found"
          else
            echo "index.html missing"
            exit 1
          fi
          echo "CI Completed Successfully"

      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"GitHub CI Pipeline Completed Successfully"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}